name: Build and Publish
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_publish:
    name: Build and Publish to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        base-image: ["alpine", "ubuntu"]
        # Two latest versions, previous two latest minor versions, and previous latest major version
        version: ["2.14.3", "2.14.2", "2.13.0", "2.12.1", "1.14.0"]
    env:
      LATEST_VERSION: "2.14.3"
      REGISTRY: ghcr.io
      IMAGE_NAME: jackm25/github-cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2.0.0
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: tags
        uses: actions/github-script@v6.1.0
        env:
          BASE_IMAGE: '${{ matrix.base-image }}'
          VERSION: '${{ matrix.version }}'
        with:
          result-encoding: string
          script: |
            const { VERSION, BASE_IMAGE, LATEST_VERSION } = process.env
            let tags = VERSION + '-' + BASE_IMAGE + '\n'
            if (BASE_IMAGE === 'alpine') tags += VERSION + '\n'
            if (VERSION === LATEST_VERSION) tags += 'latest-' + BASE_IMAGE + '\n'
            if (BASE_IMAGE === 'alpine' && VERSION === LATEST_VERSION) tags += 'latest\n'
            return tags

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.0.0
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: ${{steps.tags.outputs.result}}

      - name: Build Docker Image
        uses: docker/build-push-action@v3.1.0
        with:
          context: ./${{ matrix.base-image }}
          load: true
          build-args: GH_CLI_VERSION=${{ matrix.version }}
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ matrix.base-image }}-rc
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Test Docker Image
        run: |
          ./${{ matrix.base-image }}/test-image.sh ${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ matrix.base-image }}-rc
      
      - name: Push Docker Image
        uses: docker/build-push-action@v3.1.0
        if: github.event_name != 'pull_request'
        with:
          context: ./${{ matrix.base-image }}
          push: true
          build-args: GH_CLI_VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
